name: Django Backend Tests

on:
  push:
    branches: [main, dev, joe-continuous-integration-and-testing]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: "True"
      DJANGO_LOGLEVEL: ${{ secrets.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_DB: ${{ secrets.REDIS_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for backend to start
        run: sleep 15

      - name: Run Django Tests
        run: docker compose exec -T django-web python manage.py test fango --verbosity=2

      - name: Stop containers
        if: always()
        run: docker compose down
